-- 코드를 입력하세요
SELECT
    DISTINCT G.USER_ID,
    G.NICKNAME, G.CITY||' '||G.STREET_ADDRESS1||' '||G.STREET_ADDRESS2 AS "전체주소",
    SUBSTR(G.TLNO,1,3)||'-'||SUBSTR(G.TLNO,4,4)||'-'||SUBSTR(G.TLNO,8) AS "전화번호"
FROM
    USED_GOODS_BOARD B JOIN USED_GOODS_USER G
ON
    B.WRITER_ID = G.USER_ID
WHERE
    B.WRITER_ID IN (SELECT WRITER_ID FROM USED_GOODS_BOARD GROUP BY WRITER_ID HAVING COUNT(WRITER_ID) >= 3)
ORDER BY 1 DESC;