-- 코드를 입력하세요
SELECT 
TO_NUMBER(TO_CHAR(S.SALES_DATE, 'YYYY')) AS YEAR,
TO_NUMBER(TO_CHAR(S.SALES_DATE, 'MM')) AS MONTH,
COUNT(DISTINCT S.USER_ID) AS "PUCHASED_USERS",
ROUND(COUNT(DISTINCT S.USER_ID)/(SELECT COUNT(USER_ID) FROM USER_INFO WHERE TO_CHAR(JOINED, 'YYYY') = '2021'),1) AS "PUCHASED_RATIO"
FROM USER_INFO I JOIN ONLINE_SALE S
ON (I.USER_ID = S.USER_ID)
WHERE TO_CHAR(I.JOINED, 'YYYY') = '2021'
GROUP BY TO_NUMBER(TO_CHAR(S.SALES_DATE, 'YYYY')),TO_NUMBER(TO_CHAR(S.SALES_DATE, 'MM'))
ORDER BY 1, 2;