-- 코드를 입력하세요
SELECT HOUR, COUNT(O.ANIMAL_ID) AS COUNT
FROM (SELECT LEVEL - 1 HOUR FROM DUAL CONNECT BY LEVEL <= 24) HR
LEFT JOIN ANIMAL_OUTS O
ON(HR.HOUR = TO_CHAR(O.DATETIME, 'HH24'))
GROUP BY HOUR
ORDER BY 1;