-- 코드를 입력하세요
SELECT DISTINCT C.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR C JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
ON C.CAR_ID = H.CAR_ID
WHERE C.CAR_TYPE = '세단' AND TO_CHAR(H.START_DATE,'YYYY-MM-DD') >= '2022-10-01' 
GROUP BY C.CAR_TYPE, C.CAR_ID
ORDER BY 1 DESC;
